db:
    image: mysql:5.7
    ports:
        - "3306:3306"
    environment:
        - "MYSQL_ROOT_PASSWORD=your_root_password"
        - "MYSQL_USER=your_user"
        - "MYSQL_PASSWORD=your_user_password"
        - "MYSQL_DATABASE=your_database_name"

engine:
    build: ./docker/engine/php/7.0/fpm
    volumes:
        - "./symfony:/home/docker:rw"
        - "./docker/engine/php.ini:/usr/local/etc/php/conf.d/custom.ini:ro"
    links:
        - "db:db"
    working_dir: "/home/docker"

front:
    image: nginx
    ports:
        - "80:80"
    links:
        - "engine:engine"
    volumes:
        - "./symfony:/home/docker:ro"
        - "./docker/front/default.conf:/etc/nginx/conf.d/default.conf:ro"
